#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

DOC_PATH="docs/PROJECT-MANIFEST.md"

markdown_escape() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//|/\\|}"
  printf '%s' "$value"
}

project_files() {
  {
    printf '%s\n' "$DOC_PATH"
    find . \
      -path './.git' -prune -o \
      -path './.prometheus' -prune -o \
      -type f -print
  } | sed 's#^\./##' | sort -u
}

kind_for_file() {
  case "$1" in
    scripts/*.sh) printf 'script' ;;
    docs/sessions/.gitkeep) printf 'session-placeholder' ;;
    docs/*.md) printf 'generated-doc' ;;
    infra/*.json) printf 'infra-json' ;;
    infra/*.md) printf 'infra-doc' ;;
    prompts/codex-phase-0-build.md) printf 'build-brief' ;;
    *.yaml) printf 'contract-yaml' ;;
    .gitignore) printf 'project-ignore' ;;
    PROGRESS-*.md) printf 'progress-log' ;;
    README.md) printf 'protocol-index' ;;
    L1-HANDOFF.md) printf 'handoff' ;;
    GOAL.md|RELATIONSHIPS.md|PREFLIGHT-LEARNINGS.md|INJECTION-SNIPPET.md) printf 'support-doc' ;;
    *.md) printf 'protocol-doc' ;;
    *) printf 'project-file' ;;
  esac
}

notes_for_file() {
  case "$1" in
    "$DOC_PATH") printf 'Self entry; line count intentionally omitted to avoid circular freshness churn.' ;;
    scripts/*.sh) printf 'Syntax and executable bit are covered by validate-protocols.' ;;
    docs/PROMETHEUS.md|docs/PROTOCOL-INVENTORY.md) printf 'Generated document; freshness is covered by local build.' ;;
    docs/sessions/.gitkeep) printf 'Keeps the session-doc directory present.' ;;
    infra/*.md|infra/*.json) printf 'Context manifest; selected invariants covered by context-docs-check.' ;;
    prompts/codex-phase-0-build.md) printf 'Primary local build brief; presence and readability are covered by build-brief-check.' ;;
    .gitignore) printf 'Project-local ignored-artifact list.' ;;
    PROGRESS-*.md) printf 'Append-only worker session ledger.' ;;
    README.md) printf 'Human protocol index and runtime logging contract.' ;;
    L1-HANDOFF.md) printf 'L1 pickup and external-integration boundary.' ;;
    prometheus.yaml) printf 'Prometheus component contract parsed during validation.' ;;
    *) printf 'Project source artifact reviewed by local validation or progress ledger.' ;;
  esac
}

generate_document() {
  cat <<'HEADER'
# Project Manifest

Generated by `bash scripts/project-manifest.sh document`.

This is the project-local file inventory used to make future reviews and handoffs deterministic. It excludes `.git/` internals and ignored `.prometheus/` learning logs.

| File | Kind | Lines | Notes |
| --- | --- | ---: | --- |
HEADER

  while IFS= read -r file; do
    [[ -n "$file" ]] || continue
    if [[ "$file" == "$DOC_PATH" ]]; then
      lines="self"
    elif [[ "$file" == PROGRESS-*.md ]]; then
      lines="append-only"
    elif [[ -f "$file" ]]; then
      lines="$(wc -l < "$file" | tr -d ' ')"
    else
      lines="missing"
    fi
    printf '| `%s` | %s | %s | %s |\n' \
      "$(markdown_escape "$file")" \
      "$(markdown_escape "$(kind_for_file "$file")")" \
      "$(markdown_escape "$lines")" \
      "$(markdown_escape "$(notes_for_file "$file")")"
  done < <(project_files)
}

document() {
  mkdir -p docs
  if [[ "${1:-}" == "--check" ]]; then
    tmp="$(mktemp)"
    generate_document > "$tmp"
    cmp -s "$tmp" "$DOC_PATH" || {
      rm -f "$tmp"
      echo "$DOC_PATH is stale; run: bash scripts/project-manifest.sh document" >&2
      return 1
    }
    rm -f "$tmp"
    return 0
  fi
  generate_document > "$DOC_PATH"
}

case "${1:-document}" in
  document) shift; document "$@" ;;
  *) echo "usage: $0 document [--check]" >&2; exit 2 ;;
esac
