#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

COMPONENT_ID="fleet-protocols"
DOC_PATH="docs/PROMETHEUS.md"
REQUIRED_FILES=("README.md" "PREFLIGHT.md" "BLOCKER-CHECK.md" "ROOT-CAUSE.md" "DATA-TRUST.md" "SHIP-OR-SHAM.md")
JSON_FILES=()
NODE_CHECK_FILES=()

generate_document() {
  cat <<'DOC'
# Prometheus Contract: fleet-protocols

Generated by `bash scripts/prometheus.sh document`.

## Required Properties

| Property | Implementation |
| --- | --- |
| self-test | `bash scripts/prometheus.sh test` checks required source/docs, parseable JSON, configured source syntax, and learning dry-run output. |
| self-document | `bash scripts/prometheus.sh document` regenerates this file from the repository contract. |
| self-correct | `bash scripts/prometheus.sh correct` regenerates documentation, emits a correction learning event, then reruns the self-test. |
| self-learn | `bash scripts/prometheus.sh learn` writes a local JSONL event and, when fleet credentials exist, inserts `fleet_tool_brain_state`. |

## Verification Scope

- Required files: `README.md`, `PREFLIGHT.md`, `BLOCKER-CHECK.md`, `ROOT-CAUSE.md`, `DATA-TRUST.md`, `SHIP-OR-SHAM.md`
- JSON files: none
- Node syntax checks: none

## Non-Goals

The Prometheus self-test does not call live external APIs, deploy services, restart daemons, or mutate production data.
DOC
}

document() {
  mkdir -p docs
  if [[ "${1:-}" == "--check" ]]; then
    tmp="$(mktemp)"
    generate_document > "$tmp"
    cmp -s "$tmp" "$DOC_PATH" || {
      rm -f "$tmp"
      echo "$DOC_PATH is stale; run: bash scripts/prometheus.sh document" >&2
      return 1
    }
    rm -f "$tmp"
    return 0
  fi
  generate_document > "$DOC_PATH"
}

learn() {
  local event="self_learn"
  local dry_run="false"
  for arg in "$@"; do
    case "$arg" in
      --dry-run) dry_run="true" ;;
      --event=*) event="${arg#--event=}" ;;
      *) event="$arg" ;;
    esac
  done

  payload="$(
    COMPONENT_ID="$COMPONENT_ID" EVENT_NAME="$event" node - <<'NODE'
const payload = {
  component_id: process.env.COMPONENT_ID,
  event: process.env.EVENT_NAME || "self_learn",
  observed_at: new Date().toISOString(),
  repo: process.cwd(),
  source: "scripts/prometheus.sh",
  status: "ok"
};
process.stdout.write(JSON.stringify(payload));
NODE
  )"

  if [[ "$dry_run" == "true" ]]; then
    printf '%s\n' "$payload"
    return 0
  fi

  mkdir -p .prometheus
  printf '%s\n' "$payload" >> .prometheus/learning.jsonl

  local cred="$HOME/.credentials/supabase-full.json"
  [[ -f "$cred" ]] || cred="$HOME/.credentials/supabase.json"
  if [[ -f "$cred" ]]; then
    url="$(node -e 'const fs=require("fs"); const c=JSON.parse(fs.readFileSync(process.argv[1],"utf8")); process.stdout.write(c.project_url||c.url||"");' "$cred")"
    key="$(node -e 'const fs=require("fs"); const c=JSON.parse(fs.readFileSync(process.argv[1],"utf8")); process.stdout.write(c.service_role_key||c.service_role||c.serviceRoleKey||"");' "$cred")"
    if [[ -n "$url" && -n "$key" ]]; then
      body="$(PAYLOAD="$payload" TOOL_NAME="$COMPONENT_ID" node -e 'process.stdout.write(JSON.stringify({tool_name:process.env.TOOL_NAME,state_key:"prometheus:last_self_learn",state_value:JSON.parse(process.env.PAYLOAD),last_updated:new Date().toISOString()}));')"
      curl -fsS -X POST "$url/rest/v1/fleet_tool_brain_state?on_conflict=tool_name,state_key" \
        -H "apikey: $key" \
        -H "Authorization: Bearer $key" \
        -H "Content-Type: application/json" \
        -H "Prefer: resolution=merge-duplicates,return=minimal" \
        --data "$body" >/dev/null || true
    fi
  fi

  printf '%s\n' "$payload"
}

run_project_checks() {
  for file in "${REQUIRED_FILES[@]}"; do
    test -f "$file"
  done
  if ((${#JSON_FILES[@]})); then
    for file in "${JSON_FILES[@]}"; do
      node -e 'JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"))' "$file"
    done
  fi
  if ((${#NODE_CHECK_FILES[@]})); then
    for file in "${NODE_CHECK_FILES[@]}"; do
      node --check "$file" >/dev/null
    done
  fi
}

self_test() {
  test -f prometheus.yaml
  document --check
  learn --dry-run >/dev/null
  run_project_checks
}

correct() {
  document
  learn --event=self_correct >/dev/null
  self_test
}

case "${1:-test}" in
  test) self_test ;;
  document) shift; document "$@" ;;
  correct) correct ;;
  learn) shift; learn "$@" ;;
  *) echo "usage: $0 {test|document|correct|learn}" >&2; exit 2 ;;
esac
