#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

COMPONENT_ID="fleet-protocols"
DOC_PATH="docs/PROMETHEUS.md"
REQUIRED_FILES=("README.md" "PREFLIGHT.md" "BLOCKER-CHECK.md" "ROOT-CAUSE.md" "DATA-TRUST.md" "SHIP-OR-SHAM.md")
JSON_FILES=()
NODE_CHECK_FILES=()

generate_document() {
  cat <<'DOC'
# Prometheus Contract: fleet-protocols

Generated by `bash scripts/prometheus.sh document`.

## Required Properties

| Property | Implementation |
| --- | --- |
| self-test | `bash scripts/prometheus.sh test` checks required source/docs, build-brief fallback readiness, protocol-library invariants, README-indexed protocol contracts, README combo/logging references, injection-surface drift, runtime RPC/table/view contract drift, source-of-truth boundary drift, local-build script coverage, project-local reference drift, Prometheus YAML contract drift, worker-lane guardrails, L1 handoff freshness, progress-log structure including latest-session timestamp, highest-session selection, highest-session uniqueness, highest-session EOF append order, and an explicit passing final local-build result, latest-session review coverage, latest-session touched-file manifest coverage, repo context-doc freshness, parseable JSON/YAML, all local shell script shebangs, strict mode, project-root anchors, syntax, and executable bits, generated-doc freshness, project-manifest freshness, and learning dry-run output. |
| self-document | `bash scripts/prometheus.sh document` regenerates this file from the repository contract. |
| self-correct | `bash scripts/prometheus.sh correct` regenerates documentation, emits a correction learning event, then reruns the self-test. |
| self-learn | `bash scripts/prometheus.sh learn` writes a local JSONL event and, when fleet credentials exist, inserts `fleet_tool_brain_state`. |

## Verification Scope

- Required files: `README.md`, `PREFLIGHT.md`, `BLOCKER-CHECK.md`, `ROOT-CAUSE.md`, `DATA-TRUST.md`, `SHIP-OR-SHAM.md`
- Protocol invariants: README index targets exist, indexed protocols are present, README protocol labels match filenames, README-indexed protocol H1/trigger/action markers are valid, README recommended combos and shorthand logging rows reference indexed protocols, README/injection/infra docs preserve the runtime RPC/table/view contract, README and `INJECTION-SNIPPET.md` preserve the five injection surfaces and trigger-to-RPC mappings, source-of-truth boundary docs preserve the current fleet-brain/protocols safe default and L1-owned external integration, every project-local shell script except the local-build entrypoint itself is represented in `../scripts/local-build.sh`, project-local Markdown links and clear local file/script literals resolve, short protocol files stay under 80 lines, trigger headers are present, build-brief fallback is readable when `prompts/codex-phase-0-build.md` is absent, `prometheus.yaml` parses and matches local script/docs contract, worker-lane guardrails keep local build free of version-control/deploy/restart commands, infra JSON parses, every `../scripts/*.sh` file declares the bash shebang, enables strict mode, anchors execution at the project root, passes a syntax check, and is executable, generated docs are current, `docs/PROJECT-MANIFEST.md` covers project-local source files, `L1-HANDOFF.md` preserves the live integration obligations, `PROGRESS-2026-05-16.md` preserves required latest-session sections, timestamp, highest-numbered session selection, highest-session uniqueness, EOF append order, and a passing final local-build result, the latest progress session lists every project-manifest file as reviewed and every touched file as a project-manifest entry, and repo context docs point agents at current local validation.
- JSON files: none
- Node syntax checks: none

## Local Build

Run `bash ../scripts/local-build.sh` from this docs directory, or `bash scripts/local-build.sh` from the project root, for the full project-local gate: protocol validation, build-brief validation, worker guardrail validation, local-build contract validation, injection surface validation, protocol contract validation, runtime contract validation, source-boundary validation, local reference validation, Prometheus contract validation, Prometheus self-test, project-manifest freshness, generated-doc freshness, handoff validation, progress-log validation, session review coverage, and context-doc validation.

## Non-Goals

The Prometheus self-test does not call live external APIs, deploy services, restart daemons, or mutate production data.
DOC
}

document() {
  mkdir -p docs
  if [[ "${1:-}" == "--check" ]]; then
    tmp="$(mktemp)"
    generate_document > "$tmp"
    cmp -s "$tmp" "$DOC_PATH" || {
      rm -f "$tmp"
      echo "$DOC_PATH is stale; run: bash scripts/prometheus.sh document" >&2
      return 1
    }
    rm -f "$tmp"
    return 0
  fi
  generate_document > "$DOC_PATH"
}

learn() {
  local event="self_learn"
  local dry_run="false"
  for arg in "$@"; do
    case "$arg" in
      --dry-run) dry_run="true" ;;
      --event=*) event="${arg#--event=}" ;;
      *) event="$arg" ;;
    esac
  done

  payload="$(
    COMPONENT_ID="$COMPONENT_ID" EVENT_NAME="$event" node - <<'NODE'
const payload = {
  component_id: process.env.COMPONENT_ID,
  event: process.env.EVENT_NAME || "self_learn",
  observed_at: new Date().toISOString(),
  repo: process.cwd(),
  source: "scripts/prometheus.sh",
  status: "ok"
};
process.stdout.write(JSON.stringify(payload));
NODE
  )"

  if [[ "$dry_run" == "true" ]]; then
    printf '%s\n' "$payload"
    return 0
  fi

  mkdir -p .prometheus
  printf '%s\n' "$payload" >> .prometheus/learning.jsonl

  local cred="$HOME/.credentials/supabase-full.json"
  [[ -f "$cred" ]] || cred="$HOME/.credentials/supabase.json"
  if [[ -f "$cred" ]]; then
    url="$(node -e 'const fs=require("fs"); const c=JSON.parse(fs.readFileSync(process.argv[1],"utf8")); process.stdout.write(c.project_url||c.url||"");' "$cred")"
    key="$(node -e 'const fs=require("fs"); const c=JSON.parse(fs.readFileSync(process.argv[1],"utf8")); process.stdout.write(c.service_role_key||c.service_role||c.serviceRoleKey||"");' "$cred")"
    if [[ -n "$url" && -n "$key" ]]; then
      body="$(PAYLOAD="$payload" TOOL_NAME="$COMPONENT_ID" node -e 'process.stdout.write(JSON.stringify({tool_name:process.env.TOOL_NAME,state_key:"prometheus:last_self_learn",state_value:JSON.parse(process.env.PAYLOAD),last_updated:new Date().toISOString()}));')"
      curl -fsS -X POST "$url/rest/v1/fleet_tool_brain_state?on_conflict=tool_name,state_key" \
        -H "apikey: $key" \
        -H "Authorization: Bearer $key" \
        -H "Content-Type: application/json" \
        -H "Prefer: resolution=merge-duplicates,return=minimal" \
        --data "$body" >/dev/null || true
    fi
  fi

  printf '%s\n' "$payload"
}

run_project_checks() {
  for file in "${REQUIRED_FILES[@]}"; do
    test -f "$file"
  done
  # validate-protocols.sh owns the repeated documentation/protocol invariants
  # below. Keep only checks that are not covered there, then run the full
  # validator once so Prometheus audits do not duplicate the same work.
  bash scripts/build-brief-check.sh >/dev/null
  bash scripts/worker-guardrail-check.sh >/dev/null
  bash scripts/runtime-contract-check.sh >/dev/null
  bash scripts/session-review-coverage-check.sh >/dev/null
  bash scripts/validate-protocols.sh >/dev/null
  if ((${#JSON_FILES[@]})); then
    for file in "${JSON_FILES[@]}"; do
      node -e 'JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"))' "$file"
    done
  fi
  if ((${#NODE_CHECK_FILES[@]})); then
    for file in "${NODE_CHECK_FILES[@]}"; do
      node --check "$file" >/dev/null
    done
  fi
}

self_test() {
  test -f prometheus.yaml
  document --check
  learn --dry-run >/dev/null
  run_project_checks
}

correct() {
  document
  learn --event=self_correct >/dev/null
  self_test
}

case "${1:-test}" in
  test) self_test ;;
  document) shift; document "$@" ;;
  correct) correct ;;
  learn) shift; learn "$@" ;;
  *) echo "usage: $0 {test|document|correct|learn}" >&2; exit 2 ;;
esac
