#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

DOC_PATH="docs/PROTOCOL-INVENTORY.md"

markdown_escape() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//|/\\|}"
  printf '%s' "$value"
}

readme_protocol_rows() {
  awk -F'|' '
    /^\|/ && $4 ~ /`[^`]+\.md`/ {
      moment=$2
      protocol=$3
      file=$4
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", moment)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", protocol)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", file)
      gsub(/\*\*/, "", protocol)
      gsub(/`/, "", file)
      print protocol "\t" file "\t" moment
    }
  ' README.md
}

trigger_for_file() {
  local file="$1"
  local trigger
  trigger="$(sed -n '1,12p' "$file" | sed -nE 's/^> \*\*TRIGGER:\*\* ?//p' | head -1)"
  if [[ -z "$trigger" ]]; then
    trigger="$(sed -n '1,12p' "$file" | sed -nE 's/^> \*\*(MANDATORY[^*]*)\*\*.*/\1/p' | head -1)"
  fi
  if [[ -z "$trigger" ]]; then
    trigger="$(sed -n '1,12p' "$file" | sed -nE 's/^> (.*TRIGGER:.*)$/\1/p' | head -1)"
  fi
  printf '%s' "${trigger:-not declared in first 12 lines}"
}

generate_document() {
  cat <<'HEADER'
# Protocol Inventory

Generated by `bash scripts/protocol-inventory.sh document`.

This file is the project-local, machine-checkable view of the README routing table. It does not replace the README as the human protocol index.

| Protocol | File | Lines | README Trigger Moment | File Trigger |
| --- | --- | ---: | --- | --- |
HEADER

  while IFS=$'\t' read -r protocol file moment; do
    [[ -n "$file" ]] || continue
    if [[ -f "$file" ]]; then
      lines="$(wc -l < "$file" | tr -d ' ')"
      trigger="$(trigger_for_file "$file")"
    else
      lines="missing"
      trigger="missing file"
    fi
    printf '| %s | `%s` | %s | %s | %s |\n' \
      "$(markdown_escape "$protocol")" \
      "$(markdown_escape "$file")" \
      "$(markdown_escape "$lines")" \
      "$(markdown_escape "$moment")" \
      "$(markdown_escape "$trigger")"
  done < <(readme_protocol_rows)
}

document() {
  mkdir -p docs
  if [[ "${1:-}" == "--check" ]]; then
    tmp="$(mktemp)"
    generate_document > "$tmp"
    cmp -s "$tmp" "$DOC_PATH" || {
      rm -f "$tmp"
      echo "$DOC_PATH is stale; run: bash scripts/protocol-inventory.sh document" >&2
      return 1
    }
    rm -f "$tmp"
    return 0
  fi
  generate_document > "$DOC_PATH"
}

case "${1:-document}" in
  document) shift; document "$@" ;;
  *) echo "usage: $0 document [--check]" >&2; exit 2 ;;
esac
